<?php

namespace Luany\Core\Routing;

/**
 * RouteCache
 *
 * Serializes and loads the compiled route table to/from a PHP file,
 * eliminating the need to re-execute routes/http.php on every request.
 *
 * Only routes with array actions ([Controller::class, 'method']) are stored.
 * Closure actions cannot be serialized and are silently excluded — this is
 * intentional. In production, all routes should use controller array syntax.
 *
 * Cache file format:
 *   A plain PHP file that returns an array:
 *   <?php return ['routes' => [...], 'named' => [...]];
 *
 * Workflow:
 *   // Production bootstrap (public/index.php or Kernel::boot()):
 *   if (!Route::loadCache(base_path('storage/cache/routes.php'))) {
 *       require base_path('routes/http.php');
 *       Route::cache(base_path('storage/cache/routes.php'));
 *   }
 *
 *   // Deployment / CI (after deploying new code):
 *   @unlink(base_path('storage/cache/routes.php'));
 *   // Or: luany route:cache (Phase 6 CLI command)
 */
class RouteCache
{
    /**
     * Serialize the route table to a PHP file.
     *
     * @param array  $routes      The Router's $routes array
     * @param array  $namedRoutes The Router's $namedRoutes array
     * @param string $path        Absolute path to write the cache file
     *
     * @throws \RuntimeException If the directory cannot be created or the file cannot be written
     */
    public static function store(array $routes, array $namedRoutes, string $path): void
    {
        $dir = dirname($path);
        if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
            throw new \RuntimeException("Route cache directory could not be created: {$dir}");
        }

        // Only cache routes with array actions — closures are not serializable
        $cacheable = array_values(
            array_filter($routes, fn($route) => is_array($route['action']))
        );

        $export  = var_export(['routes' => $cacheable, 'named' => $namedRoutes], true);
        $content = "<?php\n\n// Generated by luany/core RouteCache — do not edit manually.\n// Delete this file to force re-generation.\n\nreturn {$export};\n";

        if (file_put_contents($path, $content) === false) {
            throw new \RuntimeException("Failed to write route cache file: {$path}");
        }
    }

    /**
     * Load a previously cached route table.
     *
     * Returns null if the cache file does not exist or cannot be read.
     * The caller is responsible for falling back to executing routes/http.php.
     *
     * @param  string  $path  Absolute path to the cache file
     * @return array{routes: array, named: array}|null
     */
    public static function load(string $path): ?array
    {
        if (!file_exists($path) || !is_readable($path)) {
            return null;
        }

        $data = include $path;

        if (!is_array($data) || !isset($data['routes'], $data['named'])) {
            return null;
        }

        return $data;
    }

    /**
     * Delete the cache file.
     *
     * @param string $path Absolute path to the cache file
     */
    public static function clear(string $path): void
    {
        if (file_exists($path)) {
            @unlink($path);
        }
    }
}
